### ISSUE TITLE
Forms crash if button click handler releases them

### ISSUE THREAD

**Issue by jwatte** [gameplay3d/GamePlay#1737] opened 2015-05-15 21:52 UTC
If I have a button click handler that SAFE_RELEASE()-es the for that contains the button, the form will actually be deleted, which will crash in the engine click dispatching code trying to walk up to parents of the button being clicked.

This can either be solved by the button holding a ref to the form (causing a cycle,) or by the dispatching code holding a temporary ref to the form (the button holds a temporary ref to itself, but that is not enough,) or by the dispatcher being explicitly aware of this case and breaking out early out of the click dispatching code when it happens.

**Comment by jwatte** [comment] 2015-05-16 00:09
Looking at this more, there is no way that the form can prevent this crash. The reason is that handlePointerPressRelease() will return a stale pointer in the case that the button event handler releases/deletes the form. Specifically, it finds the "active" control, calls into its notify, which calls the click handler, which releases the form, which releases the button; then the "guard" on the "active" releases, which deletes the object, but the "ctrl" variable is a copy of "active" without holding a refcount. This "ctrl" gets returned, and then the form dispatcher code tries to use this ctrl to do dispatching, and dies.

**Comment by aaqib7** [comment] 2015-05-19 18:23
I ran into the same problem where I couldn't release the forms in the controlEvent handler function.
The way around the problem is, releasing all your objects in the update() function.

**Comment by jwatte** [comment] 2015-05-21 19:54
Right -- I ended up working around it in the same way. That's highly annoying, though, and adds significant complexity to the game code.

**Comment by seanpaultaylor** [comment] 2015-10-21 14:05
Have a possible fix for this ?

**Comment by jwatte** [comment] 2015-10-21 20:03
That turned out to require way deep changes. A simple recount didn't do it.
So I dropped it and set a flag in my code and test that later...

Jw

**Closed** 2017-05-10 01:13 UTC
Labels: Bug
